const state={data:null,favorites:JSON.parse(localStorage.getItem('matchHubFavorites')||'[]'),primary:Number(localStorage.getItem('matchHubPrimary')||0),range:'week',view:'home',league:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const leagueNames={39:'プレミアリーグ',140:'ラ・リーガ',135:'セリエA',78:'ブンデスリーガ',61:'リーグ・アン'};
const japaneseTeams={"Arsenal":"アーセナル","Liverpool":"リヴァプール","Manchester City":"マンチェスター・シティ","Manchester United":"マンチェスター・ユナイテッド","Chelsea":"チェルシー","Tottenham":"トッテナム","Barcelona":"バルセロナ","Real Madrid":"レアル・マドリード","Atletico Madrid":"アトレティコ・マドリード","Inter":"インテル","AC Milan":"ACミラン","Juventus":"ユヴェントス","Bayern München":"バイエルン・ミュンヘン","Borussia Dortmund":"ドルトムント","Paris Saint Germain":"パリ・サンジェルマン","Marseille":"マルセイユ"};
const teamName=t=>japaneseTeams[t.name]||t.name;
const save=()=>{localStorage.setItem('matchHubFavorites',JSON.stringify(state.favorites));localStorage.setItem('matchHubPrimary',String(state.primary||0));};
async function loadData(force=false){$('#updateStatus').textContent='データを取得中…';try{const r=await fetch(`./data/football.json?${force?Date.now():''}`,{cache:force?'no-store':'default'});if(!r.ok)throw new Error('data');state.data=await r.json();render();const d=new Date(state.data.updatedAt);$('#updateStatus').textContent=`最終更新 ${d.toLocaleString('ja-JP')}`;}catch(e){$('#updateStatus').textContent='データを取得できませんでした';state.data={updatedAt:new Date().toISOString(),teams:[],fixtures:[],standings:[]};render();}}
function render(){const hasPrimary=state.primary&&state.data.teams.some(t=>t.id===state.primary);$('#onboarding').classList.toggle('hidden',hasPrimary);$('#homeView').classList.toggle('hidden',!hasPrimary||state.view!=='home');$('#standingsView').classList.toggle('hidden',state.view!=='standings');$('#searchView').classList.toggle('hidden',state.view!=='search');$('#settingsView').classList.toggle('hidden',state.view!=='settings');renderPicker();if(hasPrimary){renderHero();renderFavorites();renderSchedule();}renderStandings();renderGlobalSearch();}
function renderPicker(){if(!state.data)return;const leagues=[...new Set(state.data.teams.map(t=>t.leagueId))];$('#leagueFilters').innerHTML=leagues.map(id=>`<button class="chip ${state.league===id?'active':''}" data-league="${id}">${leagueNames[id]||id}</button>`).join('');const q=($('#teamSearch').value||'').toLowerCase();let teams=state.data.teams.filter(t=>(!state.league||t.leagueId===state.league)&&(t.name.toLowerCase().includes(q)||teamName(t).includes(q)));$('#teamPicker').innerHTML=teams.map(t=>pickerCard(t,true)).join('')||'<p class="empty">チームが見つかりません</p>';}
function pickerCard(t,primary=false){return `<button class="picker-card" data-team="${t.id}" data-primary="${primary}"><img src="${t.logo}" alt=""><span><strong>${teamName(t)}</strong><br><small>${t.name}</small></span></button>`;}
function renderHero(){const t=getTeam(state.primary);const next=fixturesFor(t.id).filter(f=>new Date(f.date)>new Date()).slice(0,3);const rank=getRank(t.id);document.documentElement.style.setProperty('--accent',t.color||'#e11d48');$('#favoriteHero').innerHTML=`<div class="hero-team"><img class="team-logo" src="${t.logo}" alt=""><div><p class="eyebrow">MY FAVORITE</p><h2>${teamName(t)}</h2><p class="english-name">${t.name}</p><span class="rank">${rank?rank+'位':'開幕前'}</span></div></div><div class="stack">${next.map(matchCard).join('')||'<p class="empty">次の試合は未定です</p>'}</div>`;}
function renderFavorites(){const ids=state.favorites.filter(id=>id!==state.primary);$('#favoriteTeams').innerHTML=ids.map(id=>{const t=getTeam(id);if(!t)return'';return `<article class="team-card"><div class="team-row"><img class="team-logo" src="${t.logo}" alt=""><div class="team-meta"><div class="team-name">${teamName(t)}　${getRank(id)?getRank(id)+'位':'開幕前'}</div><div class="english-name">${t.name}</div></div><div class="team-actions"><button class="mini-button" data-primary-id="${id}">最推し</button><button class="mini-button" data-remove-id="${id}">削除</button></div></div>${fixturesFor(id).filter(f=>new Date(f.date)>new Date()).slice(0,1).map(matchCard).join('')}</article>`}).join('')||'<p class="empty">ほかのお気に入りはまだありません</p>';}
function renderSchedule(){const now=new Date(),end=new Date(now);if(state.range==='today')end.setHours(23,59,59,999);if(state.range==='week')end.setDate(now.getDate()+7);if(state.range==='month')end.setMonth(now.getMonth()+1);let list=state.data.fixtures.filter(f=>(state.favorites.includes(f.home.id)||state.favorites.includes(f.away.id))&&new Date(f.date)>=new Date(now.getTime()-6*3600000)&&new Date(f.date)<=end);list.sort((a,b)=>statusOrder(a)-statusOrder(b)||new Date(a.date)-new Date(b.date));$('#scheduleList').innerHTML=list.map(matchCard).join('')||'<p class="empty">この期間の試合はありません</p>';}
function statusOrder(f){if(['1H','HT','2H','ET','P','LIVE'].includes(f.status))return 0;if(f.home.id===state.primary||f.away.id===state.primary)return 1;return 2;}
function matchCard(f){const date=new Date(f.date);const finished=['FT','AET','PEN'].includes(f.status);const live=['1H','HT','2H','ET','P','LIVE'].includes(f.status);const center=live?`${f.elapsed||''}分`:finished?'結果を見る':'VS';return `<article class="match-card" data-fixture="${f.id}"><div class="match-top"><span class="competition">${f.competitionJa||f.competition}</span><span class="match-meta">${date.toLocaleString('ja-JP',{month:'numeric',day:'numeric',weekday:'short',hour:'2-digit',minute:'2-digit'})}</span></div><div class="teams-line"><div class="club"><img src="${f.home.logo}" alt="">${teamName(f.home)}</div><div class="versus">${center}</div><div class="club"><img src="${f.away.logo}" alt="">${teamName(f.away)}</div></div></article>`;}
function renderStandings(){if(!state.data)return;const leagues=[...new Set(state.data.standings.map(s=>s.leagueId))];if(!state.league&&leagues.length)state.league=leagues[0];$('#standingsTabs').innerHTML=leagues.map(id=>`<button class="chip ${state.league===id?'active':''}" data-standing-league="${id}">${leagueNames[id]||id}</button>`).join('');const rows=state.data.standings.find(s=>s.leagueId===state.league)?.rows||[];$('#standingsTable').innerHTML=`<table><thead><tr><th>順位</th><th>クラブ</th><th>試</th><th>差</th><th>点</th></tr></thead><tbody>${rows.map(r=>`<tr class="${state.favorites.includes(r.team.id)?'favorite-row':''}"><td>${r.rank}</td><td>${teamName(r.team)}</td><td>${r.played}</td><td>${r.goalsDiff}</td><td><strong>${r.points}</strong></td></tr>`).join('')}</tbody></table>`;}
function renderGlobalSearch(){if(!state.data)return;const q=($('#globalTeamSearch').value||'').toLowerCase();const teams=state.data.teams.filter(t=>t.name.toLowerCase().includes(q)||teamName(t).includes(q));$('#globalTeamResults').innerHTML=teams.map(t=>pickerCard(t,false)).join('');}
function getTeam(id){return state.data.teams.find(t=>t.id===id)}function fixturesFor(id){return state.data.fixtures.filter(f=>f.home.id===id||f.away.id===id).sort((a,b)=>new Date(a.date)-new Date(b.date))}function getRank(id){for(const s of state.data.standings){const r=s.rows.find(x=>x.team.id===id);if(r)return r.rank}return null}
function selectTeam(id,asPrimary){if(!state.favorites.includes(id))state.favorites.push(id);if(asPrimary||!state.primary)state.primary=id;save();state.view='home';render();}
function showScore(id){const f=state.data.fixtures.find(x=>x.id===id);if(!f)return;const finished=['FT','AET','PEN'].includes(f.status),live=['1H','HT','2H','ET','P','LIVE'].includes(f.status);$('#scoreDialogBody').innerHTML=`<p class="eyebrow">${f.competitionJa||f.competition}</p><h2>${teamName(f.home)} ${finished||live?`${f.goals.home??'-'} - ${f.goals.away??'-'}`:'vs'} ${teamName(f.away)}</h2><p class="muted">${new Date(f.date).toLocaleString('ja-JP')}</p>${(f.events||[]).map(e=>`<p>${e.time}分　${e.type}: ${e.player||''} ${e.detail||''}</p>`).join('')||'<p class="empty">試合経過はまだありません</p>'}`;$('#scoreDialog').showModal();}
document.addEventListener('click',e=>{const team=e.target.closest('[data-team]');if(team)selectTeam(Number(team.dataset.team),team.dataset.primary==='true');const chip=e.target.closest('[data-league]');if(chip){state.league=Number(chip.dataset.league);renderPicker()}const st=e.target.closest('[data-standing-league]');if(st){state.league=Number(st.dataset.standingLeague);renderStandings()}const tab=e.target.closest('[data-range]');if(tab){state.range=tab.dataset.range;$$('.tab').forEach(x=>x.classList.toggle('active',x===tab));renderSchedule()}const nav=e.target.closest('[data-view]');if(nav){state.view=nav.dataset.view==='schedule'?'home':nav.dataset.view;$$('.nav-item').forEach(x=>x.classList.toggle('active',x===nav));render();if(nav.dataset.view==='schedule')setTimeout(()=>$('.tabs')?.scrollIntoView({behavior:'smooth'}),50)}const fixture=e.target.closest('[data-fixture]');if(fixture)showScore(Number(fixture.dataset.fixture));const pri=e.target.closest('[data-primary-id]');if(pri){state.primary=Number(pri.dataset.primaryId);save();render()}const rem=e.target.closest('[data-remove-id]');if(rem&&confirm('お気に入りから解除しますか？')){state.favorites=state.favorites.filter(id=>id!==Number(rem.dataset.removeId));save();render()}});
$('#teamSearch').addEventListener('input',renderPicker);$('#globalTeamSearch').addEventListener('input',renderGlobalSearch);$('#refreshButton').addEventListener('click',()=>loadData(true));$('#addTeamButton').addEventListener('click',()=>{state.view='search';render()});$('#closeScoreDialog').addEventListener('click',()=>$('#scoreDialog').close());
function setTheme(dark){document.documentElement.dataset.theme=dark?'dark':'light';$('#darkModeToggle').checked=dark;localStorage.setItem('matchHubTheme',dark?'dark':'light')}$('#themeButton').addEventListener('click',()=>setTheme(document.documentElement.dataset.theme!=='dark'));$('#darkModeToggle').addEventListener('change',e=>setTheme(e.target.checked));setTheme((localStorage.getItem('matchHubTheme')||'dark')==='dark');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');loadData();
