const {leagues,clubs}=SportsHubJLeague;
const favoriteKey='sportsHubFavoriteJClub';
let activeLeague='j1';let query='';
const tabs=document.querySelector('#leagueTabs');const grid=document.querySelector('#clubGrid');const search=document.querySelector('#clubSearch');const count=document.querySelector('#clubCount');
const favorite=()=>SportsHub.storage.get(favoriteKey);
const openDetail=id=>{location.href=`./jleague-detail.html?club=${encodeURIComponent(id)}`;};
function renderTabs(){tabs.innerHTML=leagues.map(([id,label])=>`<button class="chip${activeLeague===id?' active':''}" type="button" data-league="${id}">${label}</button>`).join('');}
function renderClubs(){const normalized=query.trim().toLowerCase();const current=favorite();const visible=clubs.filter(club=>club.league===activeLeague&&(!normalized||club.name.toLowerCase().includes(normalized)||club.area.includes(query.trim())));count.textContent=`${visible.length}クラブ`;grid.innerHTML=visible.map(club=>`<article class="club-card${current===club.id?' selected':''}"><span class="club-badge">${club.mark}</span><button class="club-copy" type="button" data-open-club="${club.id}"><strong>${club.name}</strong><small>${club.area}・${club.league.toUpperCase()}</small></button><button class="club-favorite" type="button" data-favorite-club="${club.id}" aria-label="${club.name}をお気に入り登録">${current===club.id?'★':'☆'}</button></article>`).join('')||'<div class="empty-state"><strong>該当するクラブがありません</strong><p>検索条件を変えてみてください。</p></div>';}
tabs.addEventListener('click',event=>{const button=event.target.closest('[data-league]');if(!button)return;activeLeague=button.dataset.league;renderTabs();renderClubs();});
grid.addEventListener('click',event=>{const favoriteButton=event.target.closest('[data-favorite-club]');if(favoriteButton){const club=SportsHubJLeague.find(favoriteButton.dataset.favoriteClub);if(favorite()===club.id){SportsHub.storage.remove(favoriteKey);SportsHub.toast('お気に入りを解除しました');}else{SportsHub.storage.set(favoriteKey,club.id);SportsHub.toast(`${club.name}をお気に入りに登録しました`);}renderClubs();return;}const openButton=event.target.closest('[data-open-club]');if(openButton)openDetail(openButton.dataset.openClub);});
search.addEventListener('input',()=>{query=search.value;renderClubs();});
SportsHub.applyTheme();renderTabs();renderClubs();