// Japanese display names for clubs returned by football-data.org.
// Keep aliases because the API may use formal, short, or sponsor-free names.
Object.assign(japaneseTeams, {
  // England
  "Arsenal FC":"アーセナル","Aston Villa FC":"アストン・ヴィラ","AFC Bournemouth":"ボーンマス","Brentford FC":"ブレントフォード","Brighton & Hove Albion FC":"ブライトン","Burnley FC":"バーンリー","Chelsea FC":"チェルシー","Crystal Palace FC":"クリスタル・パレス","Everton FC":"エヴァートン","Fulham FC":"フラム","Leeds United FC":"リーズ・ユナイテッド","Liverpool FC":"リヴァプール","Manchester City FC":"マンチェスター・シティ","Manchester United FC":"マンチェスター・ユナイテッド","Newcastle United FC":"ニューカッスル・ユナイテッド","Nottingham Forest FC":"ノッティンガム・フォレスト","Sunderland AFC":"サンダーランド","Tottenham Hotspur FC":"トッテナム","West Ham United FC":"ウェストハム・ユナイテッド","Wolverhampton Wanderers FC":"ウォルヴァーハンプトン",
  "Leicester City FC":"レスター・シティ","Ipswich Town FC":"イプスウィッチ・タウン","Southampton FC":"サウサンプトン","Sheffield United FC":"シェフィールド・ユナイテッド","Luton Town FC":"ルートン・タウン","Norwich City FC":"ノリッジ・シティ","Watford FC":"ワトフォード","West Bromwich Albion FC":"ウェスト・ブロムウィッチ","Middlesbrough FC":"ミドルズブラ","Blackburn Rovers FC":"ブラックバーン・ローヴァーズ","Coventry City FC":"コヴェントリー・シティ","Queens Park Rangers FC":"クイーンズ・パーク・レンジャーズ","Stoke City FC":"ストーク・シティ","Swansea City AFC":"スウォンジー・シティ","Hull City AFC":"ハル・シティ","Birmingham City FC":"バーミンガム・シティ",

  // Spain
  "Deportivo Alavés":"アラベス","Athletic Club":"アスレティック・ビルバオ","Club Atlético de Madrid":"アトレティコ・マドリード","FC Barcelona":"バルセロナ","Real Betis Balompié":"レアル・ベティス","RC Celta de Vigo":"セルタ","Elche CF":"エルチェ","RCD Espanyol de Barcelona":"エスパニョール","Getafe CF":"ヘタフェ","Girona FC":"ジローナ","Levante UD":"レバンテ","RCD Mallorca":"マジョルカ","CA Osasuna":"オサスナ","Rayo Vallecano de Madrid":"ラージョ・バジェカーノ","Real Madrid CF":"レアル・マドリード","Real Oviedo":"レアル・オビエド","Real Sociedad de Fútbol":"レアル・ソシエダ","Sevilla FC":"セビージャ","Valencia CF":"バレンシア","Villarreal CF":"ビジャレアル",
  "UD Las Palmas":"ラス・パルマス","CD Leganés":"レガネス","Real Valladolid CF":"レアル・バリャドリード","Granada CF":"グラナダ","Cádiz CF":"カディス","UD Almería":"アルメリア","SD Eibar":"エイバル","Málaga CF":"マラガ","RC Deportivo La Coruña":"デポルティーボ・ラ・コルーニャ","Real Racing Club de Santander":"ラシン・サンタンデール","Real Zaragoza":"レアル・サラゴサ","Sporting Gijón":"スポルティング・ヒホン","Real Sporting de Gijón":"スポルティング・ヒホン","CD Tenerife":"テネリフェ","Real Murcia CF":"レアル・ムルシア","Burgos CF":"ブルゴス","Albacete Balompié":"アルバセテ","CD Castellón":"カステリョン","Córdoba CF":"コルドバ","SD Huesca":"ウエスカ","CD Mirandés":"ミランデス","FC Andorra":"アンドラ",

  // Italy
  "Atalanta BC":"アタランタ","Bologna FC 1909":"ボローニャ","Cagliari Calcio":"カリアリ","Como 1907":"コモ","US Cremonese":"クレモネーゼ","ACF Fiorentina":"フィオレンティーナ","Genoa CFC":"ジェノア","Hellas Verona FC":"エラス・ヴェローナ","FC Internazionale Milano":"インテル","Juventus FC":"ユヴェントス","SS Lazio":"ラツィオ","US Lecce":"レッチェ","AC Milan":"ACミラン","SSC Napoli":"ナポリ","Parma Calcio 1913":"パルマ","Pisa SC":"ピサ","AS Roma":"ローマ","US Sassuolo Calcio":"サッスオーロ","Torino FC":"トリノ","Udinese Calcio":"ウディネーゼ",
  "AC Monza":"モンツァ","Empoli FC":"エンポリ","Venezia FC":"ヴェネツィア","Frosinone Calcio":"フロジノーネ","US Salernitana 1919":"サレルニターナ","Spezia Calcio":"スペツィア","UC Sampdoria":"サンプドリア","Palermo FC":"パレルモ","SSC Bari":"バーリ","Cesena FC":"チェゼーナ","Catanzaro":"カタンザーロ","Modena FC 2018":"モデナ","Reggiana 1919":"レッジャーナ","Südtirol":"ズュートティロール","Mantova 1911":"マントヴァ","Carrarese Calcio 1908":"カッラレーゼ","Brescia Calcio":"ブレシア",

  // Germany
  "FC Augsburg":"アウクスブルク","1. FC Union Berlin":"ウニオン・ベルリン","SV Werder Bremen":"ヴェルダー・ブレーメン","Borussia Dortmund":"ドルトムント","Eintracht Frankfurt":"アイントラハト・フランクフルト","SC Freiburg":"フライブルク","Hamburger SV":"ハンブルガーSV","1. FC Heidenheim 1846":"ハイデンハイム","TSG 1899 Hoffenheim":"ホッフェンハイム","1. FC Köln":"ケルン","RB Leipzig":"RBライプツィヒ","Bayer 04 Leverkusen":"バイヤー・レヴァークーゼン","1. FSV Mainz 05":"マインツ","Borussia Mönchengladbach":"ボルシアMG","FC Bayern München":"バイエルン・ミュンヘン","FC St. Pauli 1910":"ザンクトパウリ","VfB Stuttgart":"シュトゥットガルト","VfL Wolfsburg":"ヴォルフスブルク",
  "VfL Bochum 1848":"ボーフム","Holstein Kiel":"ホルシュタイン・キール","SV Darmstadt 98":"ダルムシュタット","Hertha BSC":"ヘルタ・ベルリン","FC Schalke 04":"シャルケ","Fortuna Düsseldorf":"フォルトゥナ・デュッセルドルフ","Hannover 96":"ハノーファー96","1. FC Nürnberg":"ニュルンベルク","Karlsruher SC":"カールスルーエ","SC Paderborn 07":"パーダーボルン","1. FC Kaiserslautern":"カイザースラウテルン","SpVgg Greuther Fürth":"グロイター・フュルト","Eintracht Braunschweig":"ブラウンシュヴァイク","Hertha Berlin":"ヘルタ・ベルリン",

  // France
  "Angers SCO":"アンジェ","AJ Auxerre":"オセール","Stade Brestois 29":"ブレスト","Le Havre AC":"ル・アーヴル","RC Lens":"ランス","Lille OSC":"リール","FC Lorient":"ロリアン","Olympique Lyonnais":"リヨン","Olympique de Marseille":"マルセイユ","FC Metz":"メス","AS Monaco FC":"モナコ","FC Nantes":"ナント","OGC Nice":"ニース","Paris FC":"パリFC","Paris Saint-Germain FC":"パリ・サンジェルマン","Stade Rennais FC 1901":"レンヌ","RC Strasbourg Alsace":"ストラスブール","Toulouse FC":"トゥールーズ",
  "AS Saint-Étienne":"サンテティエンヌ","Montpellier HSC":"モンペリエ","Stade de Reims":"スタッド・ランス","Clermont Foot 63":"クレルモン","ESTAC Troyes":"トロワ","Girondins de Bordeaux":"ボルドー","SM Caen":"カーン","Amiens SC":"アミアン","EA Guingamp":"ギャンガン","Grenoble Foot 38":"グルノーブル","SC Bastia":"バスティア","AC Ajaccio":"アジャクシオ","FC Sochaux-Montbéliard":"ソショー",

  // Frequent API aliases
  "Man City":"マンチェスター・シティ","Man United":"マンチェスター・ユナイテッド","Spurs":"トッテナム","Wolves":"ウォルヴァーハンプトン","Brighton Hove":"ブライトン","Bayern Munich":"バイエルン・ミュンヘン","Inter Milan":"インテル","Paris Saint-Germain":"パリ・サンジェルマン","Atlético Madrid":"アトレティコ・マドリード","Athletic Bilbao":"アスレティック・ビルバオ","Real Sociedad":"レアル・ソシエダ","Celta Vigo":"セルタ","Deportivo La Coruña":"デポルティーボ・ラ・コルーニャ","Racing Santander":"ラシン・サンタンデール","Fiorentina":"フィオレンティーナ"
});
